version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: stub_nginx
    restart: always
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    networks:
      - project

  php:
    build: ./images/php
    container_name: stub_php
    restart: always
    links:
      - mysql
    volumes:
      - ./public:/usr/share/nginx/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    networks:
      - project

  mysql:
    image: mysql:5.7
    container_name: stub_mysql
    restart: always
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - project

networks:
  project:
    driver: bridge
